### ISSUE TITLE
Feature Request: Highlight connected wires

### ISSUE THREAD

**Issue by idarob** [zrax/cctools#22] opened 2021-08-02 09:32 UTC
It would be super nice to have a tool where when "touching" a wire, all connected wire is lit up as if activated. Helpful to see if you got all wire tunnels correctly placed etc.

**Comment by zrax** [comment] 2021-08-02 17:14
I think this is a duplicate of #7 (although admittedly the description there is a bit vague)

**Closed by zrax** 2021-08-02 17:14 UTC
